apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: fvl20amm5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/fvl20amm5-java-quarkus-gitops